### PR TITLE
Add appveyor.yml

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Is there an "image" to display build status for appveyor too ? If yes, could add it next to travis' please ?

**Comment by gkoz** [comment]
There is but I think you need to get the url from each project's settings, e.g. https://ci.appveyor.com/project/GuillaumeGomez/pango/settings/badges

**Comment by gkoz** [comment]
Oh, and by the way and I've discovered a feature that adding `[skip ci]` or `[ci skip]` to a commit message avoids running the CI builds on both services (like for editing a readme).

**Comment by GuillaumeGomez** [comment]
Well, that's not like this is some kind of issue. I actually don't care. When I see that no code has changed, I generally just merge.

**Pull request merged**
