### PR TITLE
Update license headers and authors list

### PR DESCRIPTION
**Pull request by gkoz**
I'm opening this one in this shape for consistency with other repos, but @GuillaumeGomez I'm not sure what policy you prefer for the authors list, because AFAIK you're the only contributor to this repo.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
Hum... You are too so you also have to ask the question to yourself. What do you prefer ?

**Comment by gkoz** [comment]
I think it's definitely easier to maintain the same list in all of the repos and let `git blame` take care of more fine grained info.

**Comment by GuillaumeGomez** [comment]
I agree. BTW, is it possible to make all the COPYRIGHT files link to the one on the rust-gtk ?

**Comment by gkoz** [comment]
I don't think so. Setting this file up for magically disappearing in some circumstances wouldn't be a good idea :) We probably could create a 'management' repo that would own the authoritative copies of some files and use commit-hooks to push any changes to other repos.

**Comment by GuillaumeGomez** [comment]
I didn't know it was possible ! O.o

**Pull request merged**
